### ISSUE TITLE
Strange Race Condition during Transition

### ISSUE THREAD

**Issue by ghost** [UCI-UAVForge/GroundStation#107]
New GUI:

If you're booting up GUI for the first time on your computer and you transition from Execution to Recap via the Finish button, sometimes it will crash. When you load up the GUI again and repeat these steps, it doesn't crash. I have not observed it to crash in the debugger.

Potential Fix:
Wait for the map's HTML to fully load. Then continue with the transition. It turns out that this does not work. :/

**Comment by ghost** [comment]
Potential fix: The long term goal is to have a Map object that is shared by MissionPlanning, MapExecution, and MapRecap. The Map object will need two properties to ensure these kinds of issues do not arise:

1) Instantiated ONCE at the program start rather than created during each transition. It'll be faster to edit the same Map object than to create a new one every time.
2) Add a method to the Map class that returns false if the page is not yet loaded and true if the page is loaded. Before continuing, we wait until that function returns true. The function will wait for a signal from JavaScript to ensure that the map is fully loaded.

**Comment by JordanD2** [comment]
Yes, it's probably better to solve this problem in the long term rather than just adding another band-aid.

1) I think that a core goal of object oriented design should be flexibility, so I usually try to avoid any kind of "static" objects. I think it is more flexible if we have the ability to create multiple Map objects. Then again, given our new GUI design, we're probably only ever going to make one map because we transition to new windows anymore. Perhaps we could accomplish the same level of "object safety" if we ensure this class has a proper life cycle - constructed, constructs children, destructs children, destruction.

2) I agree entirely. That is actually what the MapExecution class did to prevent this same problem. Since I implemented that solution last time, I can take care of the JS/C++ bridging again once we get to that part if you want.

I think looking forward that we might have to convert all of the old UI elements to be "native" with the MDI display. It would definitely make the program run smoother, help with hunting down memory leaks, and make fixing certain graphics bugs more straightforward.

**Comment by JordanD2** [comment]
Closed by #114. The new MapWidget should help us avoid this issue in the future
